#Install python
From python:alpine

#Working directory
WORKDIR /app

#Copy contents
COPY ./requirements.txt ./

#install dependecies
RUN pip install -r requirements.txt

#copy other content
COPY ./ ./app

#Startup command
CMD ["uWSGI","app.ini"]
#CMD ["python", "run.py"]
